name: Generate ASCII Artwork

on: 
  push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Cowsay Program
      run: sudo apt-get install cowsay -y

    - name: Executed cowsay command
      run: cowsay -f dragon "Run for cover, I'am a dragon... RAWR" >> dragon.txt
    
    - name: Upload artifact dragon txt file
      uses: actions/upload-artifact@v4
      with:
        name: dragon-artifact
        path: dragon.txt

  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact dragon txt file
        uses: actions/download-artifact@v4
        with:
          name: dragon-artifact

      - name: Test Files exits
        run: grep -i "dragon" dragon.txt

  deploy_job_3:
    needs: test_job_2
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact dragon txt file
        uses: actions/download-artifact@v4
        with:
          name: dragon-artifact
          
      - name: Read file
        run: cat dragon.txt

      - name: Deploy
        run: echo deploying...
