name: Generate ASCII Artwork

on: 
  push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Cowsay Program
      run: sudo apt-get install cowsay -y

    - name: Executed cowsay command
      run: cowsay -f dragon "Run for cover, I'am a dragon... RAWR" >> dragon.txt
    
    - name: Sleep for 30 seconds
      run: sleep 30

        